spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bormeytechgirl@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
